"""Wifi station-mode applier.

When the operator submits home-wifi credentials via the settings UI,
this module templates `/etc/wpa_supplicant/wpa_supplicant-wlan0.conf`
and restarts `wpa_supplicant@wlan0` so the Pi joins the home network.

Design choices:

- **AP stays up.** The AP runs on `ap0` (a virtual interface). Station
  mode runs on `wlan0`. They're independent on the Pi Zero 2 W's
  BCM43438 (single-radio, dual-vif), so a successful station-mode
  transition doesn't kill the captive-portal lifeline. A FAILED
  station-mode transition also leaves ap0 untouched — the operator
  never loses access mid-config.

- **wpa_passphrase pre-hashes the PSK** when available so the conf
  doesn't store the cleartext home-wifi password on disk. Falls
  back to `psk="<cleartext>"` if wpa_passphrase isn't installed (it
  ships in the wpasupplicant package on Debian / Pi OS Lite, so the
  fallback shouldn't fire on a real deployment). The API request
  itself transmits cleartext over local HTTP — storage-at-rest is
  the only protection layer this module can provide.

- **Idempotent on re-submit.** If the same creds are submitted again,
  this module compares the rendered conf body against the on-disk
  body + skips the systemctl restart entirely. The operator mashing
  "Save" doesn't churn the supplicant.

- **Per-interface lock.** Two concurrent submits (operator hitting
  Save twice) would race against each other for the conf-write +
  restart. The module-global `_LOCK` serializes apply() calls so
  the second submit either no-ops (same creds; idempotent) or
  cleanly re-templates after the first finishes.

- **Sudo scope is narrow.** This module shells out to
  `sudo systemctl restart wpa_supplicant@wlan0` and
  `sudo systemctl stop wpa_supplicant@wlan0` — exactly two
  invocations. The companion `system/openmarquee-sudoers` file
  grants NOPASSWD for those two and nothing else.

The apply path runs in a background thread (kicked off from
`api_settings.py`'s PUT / PATCH handlers) so the HTTP response
returns immediately. The UI polls
`GET /api/settings/wifi-station-state` for the live status.
"""

from __future__ import annotations

import dataclasses
import logging
import os
import shutil
import subprocess
import threading
import time
from pathlib import Path
from typing import Callable, Optional

log = logging.getLogger(__name__)

# --- Paths (overridable in tests via env var) -------------------------------

WPA_SUPPLICANT_CONF_PATH = Path(
    os.environ.get(
        "OPENMARQUEE_WPA_SUPPLICANT_CONF",
        "/etc/wpa_supplicant/wpa_supplicant-wlan0.conf",
    )
)

# Header text -- matches system/wpa_supplicant-openmarquee.conf's
# preamble. The network={...} block follows it (rendered fresh on
# every apply).
_CONF_HEADER = (
    "# Generated by openmarquee wifi_station.py -- do not edit by hand.\n"
    "# Operator credentials applied via the Settings UI.\n"
    "ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev\n"
    "update_config=1\n"
    "country=US\n"
    "\n"
)


# --- Status singleton -------------------------------------------------------


@dataclasses.dataclass
class WifiStationState:
    """In-memory status surface for the UI to poll.

    `state` is monotonic within a single attempt:
        idle -> connecting -> (connected | failed)

    A subsequent apply() resets it to `connecting` again. The model
    is intentionally simple -- no history; the UI polls + displays
    the current value.
    """

    state: str = "idle"  # idle | connecting | connected | failed | disabled
    detail: Optional[str] = None  # human-readable explanation
    ssid: Optional[str] = None  # which network we're connected/connecting to


_STATE = WifiStationState()
_STATE_LOCK = threading.Lock()  # protects _STATE reads + writes
_APPLY_LOCK = threading.Lock()  # serializes apply() calls (per-interface)


def current_state() -> WifiStationState:
    """Snapshot of the current state. Safe to call from any thread."""
    with _STATE_LOCK:
        return dataclasses.replace(_STATE)


def _set_state(state: str, detail: Optional[str] = None, ssid: Optional[str] = None) -> None:
    with _STATE_LOCK:
        _STATE.state = state
        _STATE.detail = detail
        _STATE.ssid = ssid


# --- Conf rendering ---------------------------------------------------------


def _render_psk_block(ssid: str, password: str) -> str:
    """Render the `network={...}` block. Uses wpa_passphrase to pre-
    hash the PSK if the tool is available; otherwise stores cleartext
    with a `psk="..."` line.

    Returns the full network={} block as a string ready to append to
    the conf header.
    """
    wpa_passphrase = shutil.which("wpa_passphrase")
    if wpa_passphrase is not None:
        try:
            result = subprocess.run(
                [wpa_passphrase, ssid, password],
                capture_output=True,
                text=True,
                timeout=5,
                check=True,
            )
            # wpa_passphrase output IS a `network={...}` block already,
            # with the hashed psk. Strip any commented #psk= line (it
            # echoes the cleartext for human reference -- we don't want
            # cleartext in the conf).
            lines = []
            for line in result.stdout.splitlines():
                stripped = line.strip()
                if stripped.startswith("#psk="):
                    continue
                lines.append(line)
            # Ensure scan_ssid=1 is in the block (helps with hidden SSIDs).
            block = "\n".join(lines)
            if "scan_ssid=" not in block:
                # Inject before the closing brace.
                block = block.replace("}", "    scan_ssid=1\n}", 1)
            if "key_mgmt=" not in block:
                block = block.replace("}", "    key_mgmt=WPA-PSK\n}", 1)
            return block + "\n"
        except (subprocess.SubprocessError, subprocess.TimeoutExpired) as exc:
            log.warning(
                "wpa_passphrase failed (%s); falling back to cleartext psk", exc
            )
    # Fallback: cleartext psk. The API request was cleartext anyway, and
    # the on-disk file is mode 0600 owned by root, so the attack surface
    # is limited to local root or a shell-on-Pi credential.
    return (
        "network={\n"
        f'    ssid="{ssid}"\n'
        f'    psk="{password}"\n'
        "    key_mgmt=WPA-PSK\n"
        "    scan_ssid=1\n"
        "}\n"
    )


def _render_conf(ssid: str, password: str) -> str:
    """Full conf body: header + network={} block."""
    return _CONF_HEADER + _render_psk_block(ssid, password)


# --- File ops ---------------------------------------------------------------


def _read_existing_conf() -> Optional[str]:
    try:
        return WPA_SUPPLICANT_CONF_PATH.read_text()
    except FileNotFoundError:
        return None
    except OSError as exc:
        log.warning("failed to read %s: %s", WPA_SUPPLICANT_CONF_PATH, exc)
        return None


def _write_conf_atomic(body: str) -> None:
    """Write the conf atomically (temp + rename) so a crash mid-write
    can't leave wpa_supplicant reading half a file. Mode 0600 owned by
    the openmarquee user; sudo-side `systemctl restart` re-reads it
    with elevated privileges."""
    target = WPA_SUPPLICANT_CONF_PATH
    target.parent.mkdir(parents=True, exist_ok=True)
    tmp = target.with_suffix(target.suffix + ".tmp")
    tmp.write_text(body)
    os.chmod(tmp, 0o600)
    os.replace(tmp, target)


def _remove_conf_if_exists() -> bool:
    try:
        WPA_SUPPLICANT_CONF_PATH.unlink()
        return True
    except FileNotFoundError:
        return False


# --- systemctl + iw shellouts (overridable for tests) -----------------------


# Absolute path to match the sudoers Cmnd spec exactly (sudo's
# command-matching against /etc/sudoers.d/openmarquee is strict;
# the rule lists `/usr/bin/systemctl`, so the subprocess argv must
# resolve to the same path). On Pi OS trixie this is canonical
# (post-usrmerge, `/bin/systemctl` is a symlink to `/usr/bin/`).
_SYSTEMCTL_BIN = "/usr/bin/systemctl"


def _systemctl_restart_wpa_supplicant() -> None:
    subprocess.run(
        ["sudo", "-n", _SYSTEMCTL_BIN, "restart", "wpa_supplicant@wlan0"],
        check=True,
        timeout=15,
    )


def _systemctl_stop_wpa_supplicant() -> None:
    subprocess.run(
        ["sudo", "-n", _SYSTEMCTL_BIN, "stop", "wpa_supplicant@wlan0"],
        check=False,  # service may already be stopped
        timeout=15,
    )


def _iw_link_state() -> Optional[str]:
    """Parse `iw dev wlan0 link` for the connected-SSID line, if any.

    Returns the SSID string when associated; None when "Not connected"
    or on parse failure. Does not raise.
    """
    try:
        result = subprocess.run(
            ["iw", "dev", "wlan0", "link"],
            capture_output=True,
            text=True,
            timeout=5,
            check=False,
        )
    except (subprocess.SubprocessError, FileNotFoundError):
        return None
    out = (result.stdout or "") + (result.stderr or "")
    if "Not connected" in out:
        return None
    # `iw dev wlan0 link` output starts with `Connected to <bssid> (on wlan0)`
    # then `SSID: <name>` on a subsequent line.
    for line in out.splitlines():
        line = line.strip()
        if line.startswith("SSID:"):
            return line[len("SSID:"):].strip()
    return None


def _poll_for_association(
    target_ssid: str,
    timeout_sec: int = 30,
    poll_interval_sec: float = 1.0,
    iw_link_fn: Callable[[], Optional[str]] = _iw_link_state,
) -> bool:
    deadline = time.monotonic() + timeout_sec
    while time.monotonic() < deadline:
        current = iw_link_fn()
        if current == target_ssid:
            return True
        time.sleep(poll_interval_sec)
    return False


# --- Public apply entry point ----------------------------------------------


def apply_disabled(
    *,
    stop_fn: Callable[[], None] = _systemctl_stop_wpa_supplicant,
) -> None:
    """Operator turned station-mode off: stop the supplicant + remove
    the conf so a future reboot doesn't auto-re-associate."""
    with _APPLY_LOCK:
        log.info("wifi station: disabling (stop supplicant + remove conf)")
        _remove_conf_if_exists()
        try:
            stop_fn()
        except subprocess.SubprocessError as exc:
            log.warning("wifi station: stop failed (%s); ignoring", exc)
        _set_state("disabled", detail=None, ssid=None)


def apply_enabled(
    ssid: str,
    password: str,
    *,
    restart_fn: Callable[[], None] = _systemctl_restart_wpa_supplicant,
    iw_link_fn: Callable[[], Optional[str]] = _iw_link_state,
    poll_timeout_sec: int = 30,
) -> bool:
    """Template the conf + restart wpa_supplicant + poll for
    association. Idempotent: if the rendered conf body is identical
    to what's on disk, the restart is skipped and we just refresh the
    state to whatever `iw` currently reports.

    Returns True on successful association (state ends in 'connected'),
    False on timeout / failure (state ends in 'failed'). Sets the
    in-memory _STATE for the UI to poll.
    """
    with _APPLY_LOCK:
        new_body = _render_conf(ssid, password)
        existing = _read_existing_conf()
        conf_changed = (existing != new_body)

        if conf_changed:
            log.info("wifi station: writing new conf for ssid=%r", ssid)
            try:
                _write_conf_atomic(new_body)
            except OSError as exc:
                log.error("wifi station: conf write failed: %s", exc)
                _set_state("failed", detail=f"conf write failed: {exc}", ssid=ssid)
                return False
            _set_state("connecting", detail=None, ssid=ssid)
            try:
                restart_fn()
            except subprocess.SubprocessError as exc:
                log.error("wifi station: systemctl restart failed: %s", exc)
                _set_state(
                    "failed",
                    detail=f"systemctl restart failed: {exc}",
                    ssid=ssid,
                )
                return False
        else:
            log.info("wifi station: conf unchanged for ssid=%r; skip restart", ssid)
            _set_state("connecting", detail="conf unchanged; checking link", ssid=ssid)

        # Poll for association. If the supplicant was already
        # connected (idempotent re-submit case), the first iw query
        # returns the SSID immediately and we exit in ~1ms.
        ok = _poll_for_association(
            ssid,
            timeout_sec=poll_timeout_sec,
            iw_link_fn=iw_link_fn,
        )
        if ok:
            _set_state("connected", detail=None, ssid=ssid)
            log.info("wifi station: associated with ssid=%r", ssid)
            return True
        else:
            _set_state(
                "failed",
                detail=f"no association within {poll_timeout_sec}s",
                ssid=ssid,
            )
            log.warning(
                "wifi station: timed out waiting for association to ssid=%r",
                ssid,
            )
            return False


def apply_in_background(
    enabled: bool,
    ssid: Optional[str],
    password: Optional[str],
) -> threading.Thread:
    """Dispatch the apply() to a background thread so the HTTP handler
    can return immediately. Returns the started thread so callers
    (mostly tests) can join() if they need to await completion.
    """
    if not enabled:
        thread = threading.Thread(target=apply_disabled, daemon=True)
    else:
        if not ssid or not password:
            # Settings validator already rejects this combination, but
            # belt-and-braces: don't pass None into apply_enabled.
            log.warning(
                "wifi station: apply_in_background called with enabled=true "
                "but missing ssid/password; no-op"
            )
            _set_state(
                "failed",
                detail="missing ssid or password",
                ssid=ssid,
            )
            thread = threading.Thread(target=lambda: None, daemon=True)
            thread.start()
            return thread
        thread = threading.Thread(
            target=apply_enabled,
            args=(ssid, password),
            daemon=True,
        )
    thread.start()
    return thread


def has_settings_changed(
    prev_enabled: bool,
    prev_ssid: Optional[str],
    prev_password: Optional[str],
    new_enabled: bool,
    new_ssid: Optional[str],
    new_password: Optional[str],
) -> bool:
    """Did the wifi_station_* surface change in a way that requires an
    apply()? Helper for the api_settings PUT handler.

    - Toggle change in either direction -> True.
    - Stays enabled but ssid or password changed -> True.
    - Stays disabled -> False (no work needed).
    - Stays enabled with same creds -> False (apply would be a no-op
      anyway via the conf-comparison short-circuit, but skipping the
      thread spawn is cleaner).
    """
    if prev_enabled != new_enabled:
        return True
    if not new_enabled:
        return False
    return (prev_ssid != new_ssid) or (prev_password != new_password)
