#!/usr/bin/env python3
"""Tests for renderer_pi_soak_ipc_parse.py — Phase D slice 2.

Plain-assert style; pytest-discoverable (`pytest scripts/`) but also
runnable directly via `python3 scripts/test_renderer_pi_soak_ipc_parse.py`.
No third-party deps. Goals:

  1. Regex/format-line: parse a verbatim ipc.soak line shaped exactly
     like 8a2e043's eprintln output. Catches a column-swap typo in
     the production format string (slice 1 subagent non-blocker #1).
  2. Backward compatibility: a pre-slice-1 capture (no paint_us_p99
     in any sample) still gates on fps + OOM + crash; the new p99
     gate skips with a warning.
  3. Forward gate logic: synthetic transcripts with known p99 spikes
     trigger the rolling_max_p99 failure correctly.

Run:
  pytest scripts/test_renderer_pi_soak_ipc_parse.py -q
  python3 scripts/test_renderer_pi_soak_ipc_parse.py
"""

from __future__ import annotations

import os
import sys
import tempfile

# Allow `python3 scripts/test_...py` from the repo root or from scripts/.
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import renderer_pi_soak_ipc_parse as p  # noqa: E402


# A verbatim sample line as the 8a2e043 binary's eprintln emits.
# Generated by reading the format string at
# renderer/src/ipc_main.rs::IpcPaintMetrics::maybe_emit_summary on
# HEAD 8a2e043. Field order must match: window_s, frames,
# transitions, fps_avg, paint_us=avg/U/max/M, paint_us_p99,
# session_frames, session_transitions.
SLICE_1_SAMPLE_LINE = (
    "May 16 19:30:00 openMarqueeDev openmarquee-render[1234]: "
    "ipc.soak window_s=30 frames=850 transitions=50 fps_avg=30.0 "
    "paint_us=avg/15000/max/30000 paint_us_p99=28000 "
    "session_frames=850 session_transitions=50"
)

# Pre-slice-1 (Phase 9a) sample line — no paint_us_p99 field.
PRE_SLICE_1_SAMPLE_LINE = (
    "May 16 19:30:00 openMarqueeDev openmarquee-render[1234]: "
    "ipc.soak window_s=30 frames=850 transitions=50 fps_avg=30.0 "
    "paint_us=avg/15000/max/30000 "
    "session_frames=850 session_transitions=50"
)


def _write_log(lines):
    """Write a list of strings as a temp file and return its path."""
    f = tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", suffix=".log", delete=False
    )
    f.write("\n".join(lines) + "\n")
    f.close()
    return f.name


def test_regex_parses_slice1_format_line_verbatim():
    """Slice 1's eprintln format produces a line the parser extracts
    all fields from in the correct positions. A column-swap typo in
    the production format string would fail one of these asserts."""
    m = p.PAT_IPC_SOAK.search(SLICE_1_SAMPLE_LINE)
    assert m is not None, "format line failed to match — column drift?"
    assert m.group("window_s") == "30"
    assert m.group("frames") == "850"
    assert m.group("transitions") == "50"
    assert m.group("fps_avg") == "30.0"
    assert m.group("paint_us_avg") == "15000"
    assert m.group("paint_us_max") == "30000"
    assert m.group("paint_us_p99") == "28000"
    assert m.group("session_frames") == "850"
    assert m.group("session_transitions") == "50"


def test_regex_parses_pre_slice1_line_with_p99_absent():
    """Pre-slice-1 captures (no paint_us_p99) still match. The
    optional group captures None; downstream code handles the
    backward-compat path."""
    m = p.PAT_IPC_SOAK.search(PRE_SLICE_1_SAMPLE_LINE)
    assert m is not None, "pre-slice-1 line must still match"
    assert m.group("paint_us_p99") is None
    assert m.group("session_frames") == "850"


def test_parse_log_records_p99_when_present():
    log = _write_log([SLICE_1_SAMPLE_LINE])
    try:
        parsed = p.parse_log(log)
        assert len(parsed["samples"]) == 1
        s = parsed["samples"][0]
        assert s["paint_us_p99"] == 28000
        assert s["paint_us_avg"] == 15000
        assert s["paint_us_max"] == 30000
    finally:
        os.unlink(log)


def test_parse_log_records_p99_none_when_absent():
    log = _write_log([PRE_SLICE_1_SAMPLE_LINE])
    try:
        parsed = p.parse_log(log)
        assert len(parsed["samples"]) == 1
        assert parsed["samples"][0]["paint_us_p99"] is None
    finally:
        os.unlink(log)


def _synthetic_sample(window_s, paint_us_p99, frames=900, transitions=0):
    """Build a sample dict matching what parse_log emits."""
    return {
        "window_s": window_s,
        "frames": frames,
        "transitions": transitions,
        "fps_avg": frames / window_s if window_s else 0.0,
        "paint_us_avg": 15000,
        "paint_us_max": max(30000, paint_us_p99 or 0),
        "paint_us_p99": paint_us_p99,
        "session_frames": frames,
        "session_transitions": transitions,
    }


def test_rolling_max_p99_finds_worst_window():
    # 24 × 30s samples = 12min total. Window-min = 10. The
    # worst rolling 10-min window contains the 50000us spike.
    samples = []
    for _ in range(20):
        samples.append(_synthetic_sample(30, 28000))
    samples.append(_synthetic_sample(30, 50000))  # the spike
    for _ in range(3):
        samples.append(_synthetic_sample(30, 28000))
    res = p.rolling_max_p99(samples, window_min=10)
    assert res is not None
    assert res["max_p99"] == 50000
    # The spike is index 20; some sliding window containing it is
    # the worst.
    assert res["start_idx"] <= 20 <= res["end_idx"]


def test_rolling_max_p99_returns_none_when_no_p99_data():
    # All samples have paint_us_p99=None (pre-slice-1 capture).
    samples = [_synthetic_sample(30, None) for _ in range(20)]
    assert p.rolling_max_p99(samples, window_min=10) is None


def test_rolling_max_p99_skips_none_inside_mixed_window():
    # Mixed: some samples have p99, some don't. The result is
    # the max over the SAMPLED ones; None samples contribute 0.
    samples = []
    for _ in range(20):
        samples.append(_synthetic_sample(30, None))
    samples.append(_synthetic_sample(30, 40000))
    for _ in range(3):
        samples.append(_synthetic_sample(30, None))
    res = p.rolling_max_p99(samples, window_min=10)
    assert res is not None
    assert res["max_p99"] == 40000


def test_summarize_p99_gate_fails_when_over_budget():
    samples = [_synthetic_sample(30, 28000) for _ in range(20)]
    samples.append(_synthetic_sample(30, 50000))  # spike > 33333
    samples += [_synthetic_sample(30, 28000) for _ in range(3)]
    parsed = {"samples": samples, "oom_hits": [], "crash_hits": []}
    out = p.summarize(parsed, min_fps=30.0, rolling_window_min=10,
                       max_p99_paint_us=33333)
    assert out["pass"] is False
    assert any("max rolling p99" in f for f in out["failures"])
    assert out["paint_us_p99_max"] == 50000
    assert out["paint_us_p99_violations"] == 1


def test_summarize_p99_gate_passes_within_budget():
    samples = [_synthetic_sample(30, 28000) for _ in range(24)]
    parsed = {"samples": samples, "oom_hits": [], "crash_hits": []}
    out = p.summarize(parsed, min_fps=30.0, rolling_window_min=10,
                       max_p99_paint_us=33333)
    assert out["pass"] is True, f"unexpected failures: {out['failures']}"
    assert out["paint_us_p99_max"] == 28000
    assert out["paint_us_p99_violations"] == 0


def test_summarize_backward_compat_no_p99_skips_gate_with_warning():
    """Pre-slice-1 capture: no paint_us_p99 in any sample. The fps
    gate still runs; the p99 gate skips with a one-line warning.
    Overall PASS if fps + OOM + crash all clean."""
    samples = [_synthetic_sample(30, None) for _ in range(24)]
    parsed = {"samples": samples, "oom_hits": [], "crash_hits": []}
    out = p.summarize(parsed, min_fps=30.0, rolling_window_min=10,
                       max_p99_paint_us=33333)
    assert out["pass"] is True, f"unexpected failures: {out['failures']}"
    assert out["rolling_max_p99"] is None
    assert out["paint_us_p99_max"] is None
    assert any("paint_us_p99 absent" in w for w in out["warnings"])


def test_summarize_records_p99_violations_count():
    # Five samples over budget out of 24 → violations=5; gate still
    # fails on the FIRST violation (rolling check), but the JSON
    # report's violation count helps diagnostic.
    samples = [_synthetic_sample(30, 28000) for _ in range(19)]
    samples += [_synthetic_sample(30, 40000) for _ in range(5)]
    parsed = {"samples": samples, "oom_hits": [], "crash_hits": []}
    out = p.summarize(parsed, min_fps=30.0, rolling_window_min=10,
                       max_p99_paint_us=33333)
    assert out["paint_us_p99_violations"] == 5


if __name__ == "__main__":
    fns = [v for k, v in sorted(globals().items()) if k.startswith("test_")]
    failed = 0
    for fn in fns:
        try:
            fn()
            print(f"PASS {fn.__name__}")
        except AssertionError as e:
            print(f"FAIL {fn.__name__}: {e}")
            failed += 1
        except Exception as e:
            print(f"ERROR {fn.__name__}: {type(e).__name__}: {e}")
            failed += 1
    print(f"\n{len(fns) - failed}/{len(fns)} passed")
    sys.exit(0 if failed == 0 else 1)
