// Video uploader end-to-end: picks a generated test clip, waits for
// ffmpeg.wasm to transcode it in the browser, confirms the Save button
// enables and the ffmpeg log populates. This is the only test that
// exercises the real wasm pipeline inside the production uploader
// (vitest mocks it out) — so it's slow but high-signal.
//
// Fixture path: /tmp/om-video-verify/input.mp4 is generated by the
// before-hook via ffmpeg CLI so the test is self-contained.

import { mkdirSync, statSync } from "node:fs";
import { spawnSync } from "node:child_process";
import path from "node:path";
import { expect, test } from "@playwright/test";
import { resetServerState } from "./_helpers.js";

const FIXTURE_DIR = "/tmp/om-video-verify";
const FIXTURE = path.join(FIXTURE_DIR, "input.mp4");

test.beforeAll(() => {
    mkdirSync(FIXTURE_DIR, { recursive: true });
    let needsGen = true;
    try {
        needsGen = statSync(FIXTURE).size < 1024;
    } catch {
        needsGen = true;
    }
    if (needsGen) {
        const r = spawnSync(
            "ffmpeg",
            [
                "-y",
                "-f", "lavfi",
                "-i", "testsrc=duration=2:size=320x240:rate=10",
                "-c:v", "libx264",
                "-pix_fmt", "yuv420p",
                "-t", "2",
                FIXTURE,
            ],
            { stdio: "inherit" },
        );
        if (r.status !== 0) {
            throw new Error("failed to generate fixture video; is ffmpeg installed?");
        }
    }
});

test.beforeEach(() => {
    resetServerState();
});

test("video uploader transcodes a picked file via ffmpeg.wasm and enables Save", async ({ page }) => {
    // ffmpeg-core.wasm is ~30MB; the first load + transcode needs headroom.
    test.setTimeout(120_000);

    await page.goto("/");
    await page.locator('.nav-link[data-section="slides/video"]').click();
    await expect(page.locator(".video-upload")).toBeVisible();

    const saveBtn = page.locator(".video-upload .field-save");
    await expect(saveBtn).toBeDisabled();

    // Pick the fixture. The file-change handler kicks off the transcode.
    await page.locator(".video-upload .field-file").setInputFiles(FIXTURE);

    // Transcode completion is signalled by the log containing the "ready."
    // line + the Save button flipping enabled.
    await expect(page.locator(".video-upload-log-body")).toContainText(
        "transcoded to",
        { timeout: 90_000 },
    );
    await expect(saveBtn).toBeEnabled({ timeout: 90_000 });
});

test("panel-mode fallback banner is hidden on the default hdmi output_mode", async ({ page }) => {
    await page.goto("/");
    await page.locator('.nav-link[data-section="slides/video"]').click();
    await expect(page.locator(".video-upload-panel-hint")).toBeHidden();
});
