// Video uploader end-to-end: picks a generated test clip, waits for
// ffmpeg.wasm to transcode it in the browser, confirms the Save button
// enables and the ffmpeg log populates. This is the only test that
// exercises the real wasm pipeline inside the production uploader
// (vitest mocks it out) — so it's slow but high-signal.
//
// Fixture path: /tmp/om-video-verify/input.mp4 is generated by the
// before-hook via ffmpeg CLI so the test is self-contained.

import { mkdirSync, statSync } from "node:fs";
import { spawnSync } from "node:child_process";
import path from "node:path";
import { expect, test } from "@playwright/test";
import { resetServerState } from "./_helpers.js";

const FIXTURE_DIR = "/tmp/om-video-verify";
const FIXTURE = path.join(FIXTURE_DIR, "input.mp4");

test.beforeAll(() => {
    mkdirSync(FIXTURE_DIR, { recursive: true });
    let needsGen = true;
    try {
        needsGen = statSync(FIXTURE).size < 1024;
    } catch {
        needsGen = true;
    }
    if (needsGen) {
        const r = spawnSync(
            "ffmpeg",
            [
                "-y",
                "-f", "lavfi",
                "-i", "testsrc=duration=2:size=320x240:rate=10",
                "-c:v", "libx264",
                "-pix_fmt", "yuv420p",
                "-t", "2",
                FIXTURE,
            ],
            { stdio: "inherit" },
        );
        if (r.status !== 0) {
            throw new Error("failed to generate fixture video; is ffmpeg installed?");
        }
    }
});

test.beforeEach(() => {
    resetServerState();
});

test("video uploader transcodes a picked file via ffmpeg.wasm and autosaves", async ({ page }) => {
    // ffmpeg-core.wasm is ~30MB; the first load + transcode needs headroom.
    test.setTimeout(120_000);

    // Slides shell collapsed Text/Image/Video sub-entries into a single
    // sidebar `slides` link + an in-page subnav. Hash-routing lands us
    // directly on the video sub-tab without depending on the subnav DOM.
    await page.goto("/#/slides/video");
    await expect(page.locator(".video-upload")).toBeVisible();

    // Status pill stands in for the old explicit Save button. Idle on mount
    // — autosave is gated by canSave (mp4Base64 ready), and there's no MP4
    // until the file picker fires.
    const status = page.locator(".video-upload .video-upload-status");
    await expect(status).toBeAttached();

    // Pick the fixture. The file-change handler kicks off the transcode.
    await page.locator(".video-upload .field-file").setInputFiles(FIXTURE);

    // Transcode completion: the status line carries "ready. {W}×{H} H.264
    // MP4 · …". The verbose ffmpeg per-frame log lives in console.debug
    // now, not in the DOM.
    await expect(page.locator(".video-upload-status")).toContainText(
        "H.264 MP4",
        { timeout: 90_000 },
    );

    // Once transcode + thumbnail are ready, autosave's canSave gate flips
    // true, the form-input listener kicks the debounce, and the slide
    // round-trips to the server. Verify via /api/content (the status
    // pill shows no save-confirmation copy — FYS bug 6).
    await expect.poll(
        async () => {
            const items = await (await page.request.get("/api/content")).json();
            return items.filter((it) => it.type === "video").length;
        },
        { timeout: 30_000 },
    ).toBeGreaterThan(0);
});
